// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC2IHAaTJObFGSpTcgPZGYjOkyyhgJcWQ',
    appId: '1:219921491471:web:0ca22e5075df5ce499a57a',
    messagingSenderId: '219921491471',
    projectId: 'companionai1',
    authDomain: 'companionai1.firebaseapp.com',
    storageBucket: 'companionai1.firebasestorage.app',
    measurementId: 'G-8T8KDPCD18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASf_OZSYOBBJpPTlq55E8nM0HPNZUuq8Q',
    appId: '1:219921491471:android:a1e7cb02c44eecce99a57a',
    messagingSenderId: '219921491471',
    projectId: 'companionai1',
    storageBucket: 'companionai1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQeTEEDIETJC8BTGn_aXAWKhPHFNWVVy0',
    appId: '1:219921491471:ios:3e78e9653a6f163499a57a',
    messagingSenderId: '219921491471',
    projectId: 'companionai1',
    storageBucket: 'companionai1.firebasestorage.app',
    iosClientId: '219921491471-88ma8sl1vpm2mg206palc75nj19mdedj.apps.googleusercontent.com',
    iosBundleId: 'com.example.companionAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQeTEEDIETJC8BTGn_aXAWKhPHFNWVVy0',
    appId: '1:219921491471:ios:3e78e9653a6f163499a57a',
    messagingSenderId: '219921491471',
    projectId: 'companionai1',
    storageBucket: 'companionai1.firebasestorage.app',
    iosClientId: '219921491471-88ma8sl1vpm2mg206palc75nj19mdedj.apps.googleusercontent.com',
    iosBundleId: 'com.example.companionAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC2IHAaTJObFGSpTcgPZGYjOkyyhgJcWQ',
    appId: '1:219921491471:web:f242e20cdae500a799a57a',
    messagingSenderId: '219921491471',
    projectId: 'companionai1',
    authDomain: 'companionai1.firebaseapp.com',
    storageBucket: 'companionai1.firebasestorage.app',
    measurementId: 'G-HWMKRECT4L',
  );
}
